CREATE DATABASE WISHLIST;

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY 
	,EMAIL VARCHAR(150) NOT NULL
	,NOME VARCHAR(150) NOT NULL	
	,SENHA VARCHAR(150) NOT NULL
	,ATIVO bit not null	
);

CREATE TABLE WISH (
	ID INT IDENTITY PRIMARY KEY 
	,CREATIONDT DATETIME NOT NULL
	,DESCWISH VARCHAR(150) NOT NULL	
	,ATIVO bit not null
	,ID_USUARIO INT NOT NULL  FOREIGN KEY REFERENCES USUARIOS(ID)	
);

Select * from USUARIOS;

DROP Database WISHLIST;


